version: "3.8"
services:
  mongo-setup:
    container_name: mongo-setup
    image: mongo
    restart: on-failure
    networks:
      default:
    volumes:
      - ./.docker/scripts/mongosetup.sh:/scripts/mongosetup.sh
    entrypoint: ["sh", "/scripts/mongosetup.sh" ]
    depends_on:
      - mongodb
    user: root
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_REPLICA_SET_NAME: rs0
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

volumes:
  mongo-data: